# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - db/*schema.rb
    - 'tmp/*  */*'
    - 'bin/**/*'
    - 'config/**/*'
    - config.ru
    - db/migrate/*
    - db/seeds.rb
    - spec/requests/request/api_spec.rb

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Rails/WhereRange:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Layout/LineLength:
  Enabled: false